services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: filmes_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filmes_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://filmes_user:postgres@db:5432/filmes_api
    depends_on:
      - db

volumes:
  postgres_data:
