version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: filmes_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filmes_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
