"""Usuario com senha com 256 chars

Revision ID: 115117b698ea
Revises: 2be569f93b06
Create Date: 2025-05-15 19:06:09.724821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115117b698ea'
down_revision = '2be569f93b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
