"""Tabelas Usuario, Filme e Aluguel

Revision ID: 40e5983d7bc9
Revises: 
Create Date: 2025-05-12 14:49:27.691433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e5983d7bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('diretor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alugueis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('filme_id', sa.Integer(), nullable=False),
    sa.Column('data_locacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alugueis')
    op.drop_table('usuarios')
    op.drop_table('filmes')
    # ### end Alembic commands ###
