"""Adicionar nota_final e total_avaliacoes em Filme

Revision ID: 502c539558c7
Revises: dd6b9e48862a
Create Date: 2025-05-13 23:14:38.604281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502c539558c7'
down_revision = 'dd6b9e48862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_final', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_avaliacoes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.drop_column('total_avaliacoes')
        batch_op.drop_column('nota_final')

    # ### end Alembic commands ###
