"""Aumenta campo celular para 20 chars

Revision ID: 99db44cc9983
Revises: 40e5983d7bc9
Create Date: 2025-05-13 18:59:31.562999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99db44cc9983'
down_revision = '40e5983d7bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('celular',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('celular',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
