"""Add GEnero como FK em FIlme

Revision ID: dd6b9e48862a
Revises: 0cf8a37c657b
Create Date: 2025-05-13 22:25:42.967429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6b9e48862a'
down_revision = '0cf8a37c657b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'generos', ['genero_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('genero_id')

    op.drop_table('generos')
    # ### end Alembic commands ###
